# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
require_relative '../node_modules/react-native/scripts/react_native_pods'
prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

target 'ChurnCenturion' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true, # Enable Hermes
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ChurnCenturionTests' do
    inherit! :complete
    # Pods for testing
  end
end # <-- Ensure `target` is properly closed

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |build_config|
      build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      build_config.build_settings['EXCLUDED_ARCHITECTURES[sdk=iphonesimulator*]'] = 'arm64'
      build_config.build_settings['ENABLE_BITCODE'] = 'NO'
     
    end
  end

  react_native_post_install(
    installer,
    use_native_modules![:reactNativePath], # Pass the correct `config`
    :mac_catalyst_enabled => false
  )
end
